<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

if (!interface_exists("CloudApiConst")) {

    /**
     * Description of cloudApiConst
     *
     * @author maksud1
     */
    interface CloudApiConst {

        // Credentials of our iHomefinder API account
        const apiUserName = 'IWantAHome'; //your iHomefinder account username
        const apiPassword = '2F3$1xc4'; // your iHomefinder account password;
        const BULK_DATA_API = 'http://axisws.idxre.com:8080/axis2/services/IHFPartnerServices?wsdl';
        const localTimeZone = 'America/Los_Angeles';
        const thisPluginRoot = '/iwantahouse-idx-api-cron';
        const mlsListingTableName = 'mlslistings';
        const mlsListingTableFields = " listingnumber int(25) NOT NULL PRIMARY KEY, 
                                    boardid int(15),
                                    listprice decimal(50,12),
                                    streetnumber int(50),
                                    streetname text,
                                    city text,
                                    state text,
                                    zip int(15),
                                    propertytype text,
                                    propertysubtype text,
                                    bedrooms int(3),
                                    fullbaths int(3),
                                    halfbaths tinyint(1), 
                                    squarefeet int(25),
                                    agentcode varchar(20),
                                    officecode varchar(20),
                                    yearbuilt int(10),
                                    dateimported varchar(28),
                                    cityid int(10),
                                    countyid int(15),
                                    mapcode varchar(100),
                                    fireplaceyn text,
                                    numfireplaces int(25),
                                    garyn text,
                                    garagespaces int(10),
                                    lotsqft int(25),
                                    lotacres decimal(24,12),
                                    poolyn text,
                                    stories text,
                                    viewyn varchar(10),
                                    viewdescription text,
                                    style text,
                                    mlsarea text,
                                    neighborhood text,
                                    subdivision text,
                                    horsepropertyyn varchar(10),
                                    propertysubtype2 text,
                                    diningroomyn varchar(10),
                                    basementyn varchar(10),
                                    onestoryyn varchar(10),
                                    waterfrontyn varchar(10),
                                    waterfrontdesc text,
                                    familyroomyn varchar(10),
                                    propertylocation text,
                                    newconstructionyn varchar(10),
                                    golfcourseyn varchar(10),
                                    officename text,
                                    agentname text,
                                    officephone text,
                                    agentphone varchar(24),
                                    updateby text,
                                    fullpartialaddress text,
                                    nnitnumber text,
                                    mlsphotourl text,
                                    mlsthumbnailurl text,
                                    mlsphotocount int(4),
                                    county text,
                                    schooldistrict text,
                                    lastupdate varchar(50),
                                    waterbody text,
                                    newyn varchar(10),
                                    inactiveyn varchar(10),
                                    associd int(20),
                                    latitude text,
                                    longitude text,
                                    region text,
                                    censustract text,
                                    unittotal int(25),
                                    virtualtourlink text,
                                    officeonlylistingyn varchar(10),
                                    bathcount int(10),
                                    sqftrange varchar(25),
                                    stylelike text,
                                    brandedvirtualtourlink text,
                                    ihfdistdate text,
                                    listingstatusdisplay text,
                                    geographiclike text,
                                    boardinternalid varchar(20),
                                    modificationdate text,
                                    vprice text,
                                    foreclosureyn varchar(10),
                                    reoyn varchar(10),
                                    shortsaleyn varchar(10),
                                    agedcommunityyn varchar(10),
                                    availableforleaseyn varchar(10),
                                    blogpolicy tinyint(1), 
                                    dockyn varchar(10),
                                    investmentyn varchar(10),
                                    leasetopurchaseallowedyn varchar(10),
                                    preforeclosureyn varchar(10),
                                    remarks text,
                                    displayaddress text,
                                    additionalequipment text,
                                    additionalrooms text,
                                    amenities text,
                                    appliances text,
                                    atticdesc text,
                                    atticyn varchar(10),
                                    basementdesc text,
                                    boatfacilities text,
                                    cabletv text,
                                    community text,
                                    construction text,
                                    cooling text,
                                    crossstreet text,
                                    den text,
                                    diningroomdesc text,
                                    disabledfeatures text,
                                    distancetowater text,
                                    driveway text,
                                    eatingarea text,
                                    elementaryschool text,
                                    energyfeatures text,
                                    entry text,
                                    exposurefaces text,
                                    exterior text,
                                    fencing text,
                                    fireplacedesc text,
                                    floodzone text,
                                    floors text,
                                    foundation varchar(180),
                                    furnished text,
                                    general text,
                                    golfcoursedesc text,
                                    guesthouse text,
                                    heating text,
                                    heatingfuel text,
                                    highschool text,
                                    horsepropertydesc text,
                                    interior text,
                                    jrhighschool text,
                                    kitchendesc text,
                                    landscaping text,
                                    laundry text,
                                    lotdesc text,
                                    masterbath text,
                                    otherbathroomsdesc text,
                                    masterbedroom text,
                                    nearesthighway text,
                                    otherstructures text,
                                    outdoor text,
                                    bathqtr text,
                                    bathhalf text,
                                    bath3qtr text,
                                    status text,
                                    familyroomdesc text,
                                    livingroomdesc text,
                                    beachdesc text,
                                    builder text,
                                    commonareafeatures text,
                                    creditamount varchar(25),
                                    dockdesc text,
                                    farmdesc text,
                                    garagedesc text,
                                    landfeatures text,
                                    leaseterms text,
                                    lotacressource text,
                                    otherbedroomsdesc text,
                                    squarefeetsource text,
                                    township text,
                                    parkingdesc text,
                                    patiodeck text,
                                    pets varchar(130),
                                    pooldesc text,
                                    recreation text,
                                    roof text,
                                    rooms text,
                                    totalrooms varchar(10),
                                    rvparking text,
                                    securitysystem text,
                                    shorerights text,
                                    sitedesc text,
                                    spa text,
                                    sprinklers text,
                                    transportation text,
                                    utilities text,
                                    walkinclosets text,
                                    waterfrontage text,
                                    waterheater text,
                                    water text,
                                    watersewer text,
                                    wetbar text,
                                    windowsdoors text,
                                    yard text,
                                    zoning text,
                                    complexname text,
                                    feesinclude text,
                                    floorofunit text,
                                    unitfeatures text,
                                    unitsincomplex text,
                                    `condition` text,
                                    dimensions text,
                                    `length` text,
                                    manufacturer text,
                                    model text,
                                    parkamenities text,
                                    parkname text,
                                    restrictions text,
                                    skirt text,
                                    spacenumber text,
                                    spacerent text,
                                    width varchar(100),
                                    allunitshave text,
                                    buildingtotalsqft int(40),
                                    income text,
                                    metering text,
                                    num1brunits text,
                                    num2brunits text,
                                    num3brunits text,
                                    numstudio text,
                                    separatemeters varchar(180),
                                    someunitshave text,
                                    tenantpays varchar(500),
                                    unit1features text,
                                    unit2features text,
                                    unit3features text,
                                    unit4features text,
                                    accessibility text,
                                    bestuse text,
                                    apn int(52),
                                    buildingpad varchar(130),
                                    buildingpermits text,
                                    buildings text,
                                    cleared text,
                                    cornersmarked text,
                                    crops text,
                                    directions text,
                                    divisible text,
                                    documentsavailable text,
                                    easements text,
                                    electric text,
                                    elevation text,
                                    improvements text,
                                    incorporated text,
                                    inspectionsreports text,
                                    irrigation text,
                                    mineralrights text,
                                    numberlots text,
                                    parcelsizedimensions text,
                                    presentuse text,
                                    roadfrontage text,
                                    roaddesc text,
                                    septicsewer text,
                                    sidewalkscurbs text,
                                    roadimprovements text,
                                    streetdesc text,
                                    soil text,
                                    surfacewater text,
                                    surveyed text,
                                    telephone varchar(50),
                                    topography text,
                                    trees text,
                                    trenchtest text,
                                    vegetation text,
                                    waterrights text,
                                    watersource text,
                                    well text,
                                    hoa text,
                                    developmentstatus text,
                                    lotnumber varchar(50),
                                    lotdescription text,
                                    listdate varchar(50),
                                    utilitiesonsite text,
                                    modifieddate varchar(50),
                                    possbilebestuse text,
                                    propertyname text,
                                    classification text,
                                    leaseprice varchar(50),
                                    expenses varchar(50),
                                    noi varchar(20),
                                    loadingdocks text,
                                    ceilingheight text,
                                    overheaddoors text,
                                    slope text,
                                    permituses text,
                                    taxes varchar(120),
                                    officeaddress text,
                                    zipplus4 int(40),
                                    hoafee text,
                                    features text,
                                    taxamount varchar(50),
                                    showinginstructions text,
                                    roomdimensions text,
                                    gas text,
                                    ownerpays text,
                                    parkingspaces int(25),
                                    securitydeposit text,
                                    age int(10),
                                    hoafrequency text,
                                    architecture text,
                                    siding text,
                                    possession text,
                                    taxyear varchar(100),
                                    hoaincludes varchar(100),
                                    agedcommunityminage varchar(100),
                                    glatitude decimal(26,6),
                                    glongitude decimal(26,6)";
        const mlsListingPhotoTableName = 'mlslistingsphotos';
        const mlsListingPhotosTableField = " ListingNumber int(25), 
                                            BoardID int(10),
                                            MainLink text, 
                                            ThumbLink text, 
                                            LargeLink text,
                                            Priority int(2)";
    
                

    }

}
?>